export default function DpdpPage() {
  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto">
        <div className="text-center mb-12">
          <h1 className="text-4xl font-extrabold text-gray-900 sm:text-5xl">
            DPDP Notice
          </h1>
          <p className="mt-4 text-xl text-gray-600">
            Notice under the Digital Personal Data Protection Act, 2023
          </p>
          <p className="mt-2 text-sm text-gray-500">
            Last updated: September 1, 2026
          </p>
        </div>

        <div className="bg-white rounded-lg shadow-md p-8 space-y-8">
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Purpose of this notice</h2>
            <p className="text-gray-600">
              This notice is provided under Section 5 of India's Digital
              Personal Data Protection Act, 2023 ("DPDP Act"). It describes
              what personal data Ferrum OS ("we", "us") collects as a Data
              Fiduciary, why we collect it, and the rights you have as a
              Data Principal. It supplements, and should be read alongside,
              our{' '}
              <a href="/privacy" className="text-blue-600 hover:text-blue-500">
                Privacy Policy
              </a>
              .
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Personal data we process</h2>
            <p className="text-gray-600">
              Depending on which parts of Ferrum OS you use, we may process:
              contact details you provide (name, email, phone, company)
              through lead-capture forms, waitlists, or the newsletter
              signup; account details if you create an account; inputs you
              enter into calculators and estimators (e.g. a project's plot
              details, financial figures) where those inputs are submitted
              to our backend rather than processed only in your browser; and
              basic technical data (such as IP address and browser
              information) generated by ordinary web-server operation.
              Where a Ferrum Transact transactional flow is live, it may
              also involve KYC documents, which are processed under
              stricter, purpose-limited handling described at the point of
              collection.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Purpose of processing</h2>
            <p className="text-gray-600">
              We process personal data to: provide and operate the product
              or feature you're using; respond to inquiries submitted
              through our contact, demo, or waitlist forms; send product or
              account communications you've opted into; and, where
              applicable to a specific product (such as Ferrum Transact),
              to facilitate the service that product describes, subject to
              that product's own disclaimers.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Consent</h2>
            <p className="text-gray-600">
              Where the DPDP Act requires your consent before we process
              your personal data, we will seek it through a clear
              affirmative action at the point of collection — for example,
              submitting a form. You may withdraw consent at any time by
              contacting us at the address below; withdrawal does not affect
              the lawfulness of processing carried out before the
              withdrawal, and may mean we can no longer provide the specific
              feature that consent supported.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Your rights as a Data Principal</h2>
            <p className="text-gray-600">
              Under the DPDP Act, you have the right to: obtain a summary of
              the personal data we hold about you and the processing
              activities associated with it; request correction, completion,
              or updating of your personal data; request erasure of your
              personal data (subject to any legal retention obligation that
              overrides that request); nominate another individual to
              exercise these rights on your behalf in the event of death or
              incapacity; and register a grievance with us, and if
              unresolved, with the Data Protection Board of India.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Data retention</h2>
            <p className="text-gray-600">
              We retain personal data only for as long as necessary for the
              purpose it was collected, or as required by applicable law
              (for example, KYC records under PMLA obligations, where
              Ferrum Transact's transactional features are live). When
              retention is no longer necessary, we delete or anonymize the
              data.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Grievance redressal</h2>
            <p className="text-gray-600">
              We are in the process of designating a Grievance Officer as
              required under the DPDP Act. Until that designation is
              published here, please direct any DPDP-related grievance to
              the contact address below, and we will route it to the
              appropriate person and respond within the timeline the Act
              requires.
            </p>
          </section>
        </div>

        <div className="mt-8 text-center text-sm text-gray-600">
          <p>
            To exercise a right under this notice, or to raise a grievance,
            contact us at{' '}
            <a href="mailto:privacy@ferrum_os.com" className="text-blue-600 hover:text-blue-500">
              privacy@ferrum_os.com
            </a>
          </p>
        </div>
      </div>
    </div>
  )
}
