import Link from 'next/link';

const reports = [
  { slug: 'india-construction-cost-benchmarks-2026', title: 'India construction cost planning brief, 2026', year: '2026', summary: 'An evidence-led blank cost-planning brief, not a city benchmark or a database of market rates.', href: '/assets/reports/india-construction-cost-benchmarks-2026.pdf' },
  { slug: 'standards-discipline-survey', title: 'Standards discipline review brief', year: '2026', summary: 'An internal review framework for standard requirements and evidence routes. It contains no survey results.', href: '/assets/reports/standards-discipline-survey.pdf' },
  { slug: 'monsoon-impact-report', title: 'Monsoon impact review brief', year: '2025', summary: 'A project-specific weather and disruption review structure, not a multi-project panel study or schedule benchmark.', href: '/assets/reports/monsoon-impact-report.pdf' },
  { slug: 'procurement-cycle-times', title: 'Procurement cycle-time review brief', year: '2025', summary: 'An internal process-mapping aid, not a benchmark of item categories or team performance.', href: '/assets/reports/procurement-cycle-times.pdf' }
];

export const metadata = { title: 'Reports - Ferrum OS Resources', description: 'Downloadable, indicative planning briefs for project-specific cost, schedule, procurement, and standards review.' };

export default function ReportsPage() {
  return <main className="min-h-screen bg-relume-surface-secondary py-16 sm:py-20 px-6 md:px-8"><div className="max-w-4xl mx-auto"><div className="text-center mb-12"><h1 className="text-4xl sm:text-5xl lg:text-6xl font-semibold tracking-relume-tight text-relume-ink">Reports</h1><p className="mt-4 text-xl text-relume-muted">Indicative planning briefs for project review</p></div><div className="bg-white rounded-relume border border-relume-border p-8 space-y-8">{reports.map((report) => <article key={report.slug} className="border-b border-relume-border pb-8 last:border-b-0 last:pb-0"><div className="flex items-baseline justify-between flex-wrap gap-2"><h2 className="text-2xl sm:text-3xl font-semibold tracking-relume-tight text-relume-ink">{report.title}</h2><span className="text-sm font-medium text-relume-muted">{report.year} / INDICATIVE PDF</span></div><p className="mt-3 text-relume-muted">{report.summary}</p><p className="mt-4 text-sm text-relume-muted"><Link href={report.href} download className="font-medium text-relume-ink hover:underline">Download PDF</Link> / Reference this report with its Ferrum OS slug: <code className="font-mono text-relume-muted">{report.slug}</code></p></article>)}<div className="pt-4 border-t border-relume-border text-sm text-relume-muted"><p>For shorter working-team material, see the <Link href="/resources/blog" className="text-relume-ink hover:underline">blog</Link> or <Link href="/resources/whitepapers" className="text-relume-ink hover:underline">whitepapers</Link>.</p></div></div></div></main>;
}
