"use client"

import { useCallback, useEffect, useRef, useState } from "react"
type Recognition={continuous:boolean;interimResults:boolean;lang:string;start:()=>void;stop:()=>void;onresult:((e:{results:ArrayLike<{0:{transcript:string}}>})=>void)|null;onend:(()=>void)|null;onerror:(()=>void)|null}
type RecognitionConstructor=new()=>Recognition
type Message={id:number;role:"operator"|"sutra";text:string;citations?:string[]}
const demoCommands=["add one floor","show plan","set setback 3","show 3d"]
const rules="2026.1-SAMPLE · Indicative Karnataka DCR/FAR structure; not published authority text."
const structural="IS 456 Cl 23.2.1 · Simplified span/depth screen; not structural design or sign-off."
function answer(command:string){const value=command.toLowerCase();if(value.includes("setback"))return{text:"Sent to the deterministic workspace engine. The indicative setback geometry is updating.",citations:[rules]};if(value.includes("span")||value.includes("load")||value.includes("struct"))return{text:"Sent to the deterministic workspace engine. Review the simplified structural screen in context.",citations:[structural]};return{text:"Sent to the deterministic workspace engine. The canvas and extract will reconcile to the new state."}}
export default function SutraPanel({onSubmit}:{onSubmit:(text:string)=>void}){
 const[value,setValue]=useState("");const[listening,setListening]=useState(false);const[demoPaused,setDemoPaused]=useState(true);const[messages,setMessages]=useState<Message[]>([{id:0,role:"sutra",text:"Describe the space you want to test. I will route it through the live workspace engine."}]);const recognition=useRef<Recognition|null>(null);const nextId=useRef(1)
 const run=useCallback((raw:string,demo=false)=>{const command=raw.trim();if(!command)return;onSubmit(command);setMessages(current=>[...current.slice(-5),{id:nextId.current++,role:"operator",text:demo?`Demo: ${command}`:command},{id:nextId.current++,role:"sutra",...answer(command)}]);setValue("")},[onSubmit])
 useEffect(()=>{const media=window.matchMedia("(prefers-reduced-motion: reduce)");let timer:ReturnType<typeof setInterval>|undefined;let index=0;const configure=()=>{if(timer)clearInterval(timer);setDemoPaused(media.matches);if(!media.matches)timer=setInterval(()=>run(demoCommands[index++%demoCommands.length],true),7000)};configure();media.addEventListener?.("change",configure);return()=>{if(timer)clearInterval(timer);media.removeEventListener?.("change",configure);recognition.current?.stop()}},[run])
 const toggleVoice=()=>{if(listening){recognition.current?.stop();setListening(false);return}const scope=window as Window&{SpeechRecognition?:RecognitionConstructor;webkitSpeechRecognition?:RecognitionConstructor};const Constructor=scope.SpeechRecognition??scope.webkitSpeechRecognition;if(!Constructor){setMessages(m=>[...m,{id:nextId.current++,role:"sutra",text:"Voice input is unavailable here. The text command remains active."}]);return}const item=new Constructor();item.continuous=false;item.interimResults=false;item.lang="en-IN";item.onresult=e=>run(e.results[0]?.[0]?.transcript??"");item.onend=()=>setListening(false);item.onerror=()=>setListening(false);recognition.current=item;item.start();setListening(true)}
 return <aside className="flex min-h-[22rem] flex-col border border-relume-border bg-relume-command text-white lg:h-full" aria-label="SUTRA design assistant" data-sutra-panel data-demo-paused={demoPaused}>
  <header className="border-b border-white/15 px-4 py-3"><div className="flex items-center justify-between gap-3"><h1 className="font-heading text-lg font-semibold">SUTRA</h1><span className="rounded-full border border-relume-accent px-2 py-1 text-[10px] font-bold tracking-wider text-relume-accent">DEMO · INDICATIVE</span></div><p className="mt-1 text-xs text-white/65">Conversational controls for the active massing model.</p></header>
  <div className="flex-1 space-y-3 overflow-y-auto p-4" aria-live="polite">{messages.map(message=><article key={message.id} className={`rounded-2xl p-3 text-sm ${message.role==="operator"?"ml-5 bg-white text-relume-ink":"mr-5 border border-white/15 bg-white/5"}`}><p>{message.text}</p>{message.citations&&<ol aria-label="Citations" className="mt-2 space-y-1 border-t border-current/15 pt-2 text-[11px] opacity-75">{message.citations.map(citation=><li key={citation}><cite className="not-italic">[{citation}]</cite></li>)}</ol>}</article>)}</div>
  <form onSubmit={e=>{e.preventDefault();run(value)}} className="border-t border-white/15 p-3"><label htmlFor="sutra-command" className="sr-only">Ask SUTRA</label><textarea id="sutra-command" rows={2} value={value} onChange={e=>setValue(e.target.value)} placeholder="Add a floor, set setback 3 m…" className="w-full resize-none rounded-xl border border-white/25 bg-white p-3 text-sm text-relume-ink placeholder:text-relume-muted focus-visible:outline focus-visible:outline-2 focus-visible:outline-relume-accent"/><div className="mt-2 flex gap-2"><button type="button" onClick={toggleVoice} aria-pressed={listening} aria-label={listening?"Stop voice input":"Start voice input"} className="min-h-11 min-w-11 rounded-full border border-white/30 hover:bg-white/10">◉</button><button type="submit" className="min-h-11 flex-1 rounded-full bg-relume-accent px-4 text-sm font-semibold text-relume-command hover:bg-white">Send to canvas</button></div><p className="mt-2 text-[10px] text-white/55">Idle demo uses the same deterministic command path{demoPaused?" · paused for reduced motion":""}.</p></form>
 </aside>
}
